### ISSUE TITLE
What is the last known working environment for the zsim in this repository?

### ISSUE THREAD

**Issue by rajesh-s** [wangziqi2013/zsim-base#4]
I'm using Ubuntu20.04 with PIN 2.14 as recommended and I come across the following issues. I have set LIBCONFIGPATH and made ./pin-2.14 available, is there anything else needed?

1. Python2 not being picked resulting in the following. Resolved it by replacing scons with "python2  \`which scons\`" in Makefile
   ```txt
       scons: Reading SConscript files ...
       File "/home/rajesh/work/zsim/SConstruct", line 11
       print "Building " + type + " zsim at " + buildDir
    ```
2. Unistd.h not found. Resolved it by replacing asm with asm-generic in misc/list_syscalls.py
   ```
       scons: Reading SConscript files ...
       Building opt zsim at build/opt
       gcc: error: /usr/include/asm/unistd.h: No such file or directory
       gcc: fatal error: no input files
       compilation terminated.
       Traceback (most recent call last):
        File "../../misc/list_syscalls.py", line 7, in <module>
        denseList = ["INVALID"]*(max([num for (num, name) in sysList]) + 1)
        ValueError: max() arg is an empty sequence
        scons: done reading SConscript files.
        scons: Building targets ...
   ```
3. Running into further compilation issues (likely related to PIN)

```
Detecting whether pin directory exists...
Found pin-2.14
PINPATH=/home/rajesh/work/zsim-base/pin-2.14 python2 `which scons`
scons: Reading SConscript files ...
Building opt zsim at build/opt
Checking for C library hdf5... no
Checking for C library hdf5_serial... yes
Checking for C library hdf5_serial_hl... yes
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/opt/access_tracing.os -c -fPIC -march=core2 -g -O3 -funroll-loops -g -std=c++0x -Wall -Wno-unknown-pragmas -fomit-frame-pointer -fno-stack-protector -MMD -DBIGARRAY_MULTIPLIER=1 -DUSING_XED -DTARGET_IA32E -DHOST_IA32E -fPIC -DTARGET_LINUX -fabi-version=2 -D_GLIBCXX_USE_CXX11_ABI=0 -Werror -DHDF5INCPREFIX="hdf5/serial/" -DPIN_PATH="/home/rajesh/work/zsim-base/pin-2.14/intel64/bin/pinbin" -DZSIM_PATH="/home/rajesh/work/zsim-base/build/opt/libzsim.so" -DMT_SAFE_LOG -Ipin-2.14/extras/xed-intel64/include -Ipin-2.14/source/include/pin -Ipin-2.14/source/include/pin/gen -Ipin-2.14/extras/components/include -I/home/rajesh/work/zsim/deps/libconfig-1.7.2/include -Ibuild/opt build/opt/access_tracing.cpp
In file included from build/opt/access_tracing.cpp:27:
build/opt/bithacks.h:56:21: error: ‘uint32_t ilog2(T) [with T = long unsigned int]’ defined but not used [-Werror=unused-function]
   56 | template<> uint32_t ilog2<uint64_t>(uint64_t val) {
      |                     ^~~~~~~~~~~~~~~
build/opt/bithacks.h:53:21: error: ‘uint32_t ilog2(T) [with T = unsigned int]’ defined but not used [-Werror=unused-function]
   53 | template<> uint32_t ilog2<uint32_t>(uint32_t val) {
      |                     ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [build/opt/access_tracing.os] Error 1
scons: building terminated because of errors.
make: *** [Makefile:8: zsim] Error 2
```

**Comment by YalandHong** [comment]
Pin 2.14 is not open-source. ZSim has to dynamically link with Pin's libraries. Thus, their binary files must be compatible, which restricts your GCC version to 4.6 (Ubuntu 12) and 4.8 (Ubuntu 14).

Since the developers of ZSim won't support Pin 3.0, if you want to build ZSim on newer systems, you have to downgrade your GCC and re-compile all the dependencies and workloads yourself. Also, some commands from the newer systems may not work, such as `ls` command, because they probably come with some features from the newer compilers.
